Setup project files with linters
dvcorreia1984/Hello-world pull request #1
Opened 2023-05-30 15:37 UTC by dvcorreia1984

In this branch, I added: 

- [ ] HTML file
- [ ] CSS file
- [ ] Readme file
- [ ] GitIgnore file
- [ ] Linters

2023-05-30 16:26 UTC, skyv26 commented on .github/workflows/linters.yml
- [ ] Please 🙏🏻 follow the project requirements properly and please add the `Github/workflows` linter.yml content inside it, to activate your `Gitub` actions. As it will help to check your code quality.

 ## Requirment

![Uploading image.png…]()

2023-05-30 16:57 UTC, skyv26 requested changes
## Hi @dvcorreia1984 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## STATUS: REQUIRE CHANGES 🔴 

![](https://media.giphy.com/media/3o7aCPbznb29hgOgG4/giphy.gif)

## Highlights
- N/A

## Required Changes ♻️
- [ ] Please remove the `node_modules` from the project as it hangs the system to make the review so that is why I am writing here. Kindly remove it.
- [ ] Please remove the `hint-report` folder because it will make trouble while linters test.
- [ ] Please add the `linters` file properly. 
- [ ] Please use all the sections of the`README` file.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 02:50 UTC, dvcorreia1984 commented on .github/workflows/linters.yml
Thank you Aakash. 

Working on this now.

2023-05-31 04:16 UTC, dvcorreia1984 commented
I made the changes requested and it seems that everything is working now.

2023-05-31 06:16 UTC, shella12 approved these changes
Hi <STUDENT_MENTION>, 


## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights

- All linters passed ✅ 
- Professional README.md ✅   
- Good commit history ✅ 
- Descriptive pull request ✅ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 06:16 UTC, shella12 commented on test.md
- [ ] [OPTIONAL] Please delete your `test.md` file as it was suppose to be ignored and not pushed to the `github`

2023-05-31 06:40 UTC, merged